services:
  sr-api:
    container_name: sr-api
    image: dzailz/sr-api:main
    ports:
      - "8787:8080"
    env_file:
      - /var/sr-api/.env.local
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "30"
    depends_on:
      otel-collector:
        condition: service_started

  # OpenTelemetry Collector Service
  otel-collector:
    image: otel/opentelemetry-collector
    volumes:
      - /var/sr-api/otel-collector-config.yaml:/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver port, ensuring no conflict with Jaeger
      - "4318:4318" # OTLP HTTP receiver port, ensuring no conflict with Jaeger
    command: ["--config=/otel-collector-config.yaml"]
    depends_on:
      jaeger:
        condition: service_started

  promtail:
    image: grafana/promtail:latest
    volumes:
      - /var/log/docker/containers:/var/log/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/telemetry/promtail-config.yml:/etc/promtail/config.yml:ro
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      loki:
        condition: service_started

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
      - loki-wal:/loki/wal
      - /var/sr-api/loki-config.yml:/mnt/config/loki-config.yml
    command: -config.file=/mnt/config/loki-config.yml

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Jaeger Collector HTTP port
      - "14250:14250" # Jaeger Collector gRPC port
    volumes:
      - ./jaeger-data/data:/badger/data
      - ./jaeger-data/key:/badger/key
    environment:
      COLLECTOR_OTLP_ENABLED: true
      SPAN_STORAGE_TYPE: badger
      BADGER_DIRECTORY_VALUE: /badger/data
      BADGER_DIRECTORY_KEY: /badger/key
      BADGER_EPHEMERAL: "false"
    user: "0"


  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - /var/sr-api/.env.local
    volumes:
      - grafana-storage:/var/lib/grafana
      - /var/sr-api/grafana-config.ini:/etc/grafana/grafana.ini



volumes:
  grafana-storage: {}
  loki-data: {}
  loki-wal: {}
  influxdb-data: {}