name: Deploy Application

on:
  workflow_run:
    workflows:
      - "Go Build and Test"
      - "Docker Image CI"
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop the current installation
        run: docker compose -f compose.yml down -v --rmi all --remove-orphans

      - name: Set up Docker Compose
        run: docker compose -f compose.yml up -d --remove-orphans

      - name: Wait for service to be available
        run: |
          timeout=60 # Timeout in seconds
          while ! curl --output /dev/null --silent --fail http://127.0.0.1:8787/status; do
            sleep 5
            timeout=$((timeout-5))
            if [ "$timeout" -le 0 ]; then
              echo "Service did not become available in time"
              exit 1
            fi
          done
          echo "Service is available"


      - name: Verify service status
        run: |
          max_attempts=5
          timeout_between_attempts=5 # seconds
          attempt=1
          success=false
          
          while [ $attempt -le $max_attempts ]; do
            RESPONSE=$(curl --silent http://127.0.0.1:8787/status)
            echo "Attempt $attempt: Service response: $RESPONSE"
          
            if [[ "$RESPONSE" == *'"Status":"Server is running"'* ]]; then
              success=true
              break
            fi
          
            echo "Service not ready, waiting $timeout_between_attempts seconds..."
            sleep $timeout_between_attempts
            attempt=$((attempt+1))
          done
          
          if [ $success = false ]; then
            echo "Service did not report 'Server is running' status after $max_attempts attempts"
            exit 1
          fi
          
          echo "Service verified successfully"

